[functions.stats]
verify_jwt = false

[functions.analyze-site]
verify_jwt = false

[functions.me]
verify_jwt = false

[functions.purge-cache]
verify_jwt = false

[functions.gam]
verify_jwt = false

[functions.contact]
verify_jwt = false

[functions.contact-submissions]
verify_jwt = false

[functions.analyze-conversations]
verify_jwt = false

[functions.invite-collaborator]
verify_jwt = false

[functions.list-users]
verify_jwt = false

[functions.impersonate]
verify_jwt = false

[functions.authorize-account]
verify_jwt = false

[functions.projects]
verify_jwt = false