[functions.stats]
verify_jwt = false

[functions.analyze-site]
verify_jwt = false

[functions.me]
verify_jwt = false

[functions.purge-cache]
verify_jwt = false

[functions.gam]
verify_jwt = false

[functions.contact]
verify_jwt = false

[functions.contact-submissions]
verify_jwt = false